export const ROUTES = {
  HOME: '/',
  AUTH: '/auth',
  ADMIN: '/admin',
  QUIZZES: '/quizzes',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  SUBSCRIPTION: '/subscription',
  STUDENTS: 'students',
  TEACHERS: 'teachers',
  COURSES: 'courses',
  PLANS: 'plans',
  GROUP_DETAILS: '/groups/:groupId',
  CREATE_QUIZ: '/groups/:groupId/create-quiz',
};
